# Generated by Django 3.2.4 on 2021-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.TextField(max_length=15)),
                ('whatsapp', models.TextField(max_length=15)),
                ('fimage', models.ImageField(upload_to='project/vcards')),
                ('bimage', models.ImageField(upload_to='project/vcards')),
            ],
        ),
    ]
