# Generated by Django 3.2.4 on 2021-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcard',
            old_name='bimage',
            new_name='front',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='fimage',
        ),
        migrations.AddField(
            model_name='vcard',
            name='back',
            field=models.ImageField(blank=True, upload_to='project/vcards'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
