# Generated by Django 2.2.2 on 2020-10-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190606_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='percentage',
        ),
    ]
